CREATE TABLE People (
  PeopleID INTEGER NOT NULL UNIQUE,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  streetAddress TEXT,
  dateOfBirth DATE NOT NULL,
  phoneNumber TEXT,
  PRIMARY KEY (PeopleID)
);

CREATE TABLE Coaches (
  CoachID INTEGER NOT NULL UNIQUE,
  PeopleID INTEGER NOT NULL UNIQUE REFERENCES People(PeopleID),
  yearsCoaching INTEGER NOT NULL,
  PRIMARY KEY (CoachID)
);

CREATE TABLE Players (
  PlayerID INTEGER NOT NULL UNIQUE,
  PeopleID INTEGER NOT NULL UNIQUE REFERENCES People(PeopleID),
  AgeID INTEGER NOT NULL UNIQUE REFERENCES AgeGroups(AgeID),
  TeamID INTEGER NOT NULL UNIQUE REFERENCES Teams(TeamID),
  PRIMARY KEY (PlayerID)
);

CREATE TABLE Teams (
  TeamID INTEGER NOT NULL UNIQUE,
  AgeID INTEGER NOT NULL UNIQUE REFERENCES AgeGroups(AgeID),
  HCoachID INTEGER NOT NULL UNIQUE REFERENCES HeadCoaches(HCoachID),
  ACoachID INTEGER NOT NULL UNIQUE REFERENCES AssistantCoaches(ACoachID),
  PlayerID INTEGER NOT NULL UNIQUE REFERENCES Players(PlayerID),
  PRIMARY KEY (TeamID)
);

CREATE TABLE AgeGroups (
  AgeID INTEGER NOT NULL UNIQUE,
  PRIMARY KEY (AgeID)
);

CREATE TABLE HeadCoaches (
  HCoachID INTEGER NOT NULL UNIQUE,
  CoachID INTEGER NOT NULL UNIQUE REFERENCES Coaches(CoachID),
  PRIMARY KEY (HCoachID)
);

CREATE TABLE AssistantCoaches (
  ACoachID INTEGER NOT NULL UNIQUE,
  CoachID INTEGER NOT NULL UNIQUE REFERENCES Coaches(CoachID),
  PRIMARY KEY (ACoachID)
);